/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jsalonen_ttyutil_TTYUtil */

#ifndef _Included_com_jsalonen_ttyutil_TTYUtil
#define _Included_com_jsalonen_ttyutil_TTYUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jsalonen_ttyutil_TTYUtil
 * Method:    isTTY
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jsalonen_ttyutil_TTYUtil_isTTY
  (JNIEnv *, jclass);

/*
 * Class:     com_jsalonen_ttyutil_TTYUtil
 * Method:    getTTYName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jsalonen_ttyutil_TTYUtil_getTTYName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
